# Generated by Django 6.0.2 on 2026-03-06 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Branches',
            fields=[
                ('branch_id', models.SmallAutoField(db_column='Branch_ID', primary_key=True, serialize=False)),
                ('branch_name', models.CharField(db_column='Branch_name', max_length=100)),
                ('branch_phone_number', models.CharField(blank=True, db_column='Branch_phone_number', max_length=15, null=True)),
                ('branch_city', models.CharField(blank=True, db_column='Branch_city', max_length=50, null=True)),
                ('is_deleted', models.BooleanField(db_column='Is_deleted', default=False)),
            ],
            options={
                'db_table': 'Branches',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Deliveries',
            fields=[
                ('delivery_id', models.AutoField(db_column='Delivery_ID', primary_key=True, serialize=False)),
                ('delivery_date_time', models.DateTimeField(blank=True, db_column='Delivery_date_time', null=True)),
                ('is_delivered', models.BooleanField(db_column='Is_delivered', default=False)),
            ],
            options={
                'db_table': 'Deliveries',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DeliveryItems',
            fields=[
                ('pk', models.CompositePrimaryKey('delivery_id', 'item_id', blank=True, editable=False, primary_key=True, serialize=False)),
                ('item_quantity', models.PositiveSmallIntegerField(db_column='Item_quantity')),
            ],
            options={
                'db_table': 'Delivery_items',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='InventoryItems',
            fields=[
                ('item_id', models.SmallAutoField(db_column='Item_ID', primary_key=True, serialize=False)),
                ('item_name', models.CharField(blank=True, db_column='Item_name', max_length=100, null=True)),
                ('item_cost', models.DecimalField(blank=True, db_column='Item_cost', decimal_places=2, max_digits=8, null=True)),
                ('item_category', models.CharField(choices=[('Product', 'Product'), ('Ingredient', 'Ingredient'), ('Packaging', 'Packaging'), ('Other', 'Other')], db_column='Item_category', max_length=10)),
                ('is_deleted', models.BooleanField(db_column='Is_deleted', default=False)),
            ],
            options={
                'db_table': 'Inventory_items',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ItemStock',
            fields=[
                ('stock_id', models.AutoField(db_column='Stock_ID', primary_key=True, serialize=False)),
                ('item_quantity', models.PositiveSmallIntegerField(db_column='Item_quantity')),
            ],
            options={
                'db_table': 'Item_stock',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ProductIngredients',
            fields=[
                ('pk', models.CompositePrimaryKey('product_id', 'ingredient_id', blank=True, editable=False, primary_key=True, serialize=False)),
                ('ingredient_quantity', models.PositiveSmallIntegerField(db_column='Ingredient_quantity')),
            ],
            options={
                'db_table': 'ProductIngredients',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('product_id', models.SmallAutoField(db_column='Product_ID', primary_key=True, serialize=False)),
                ('product_category', models.CharField(choices=[('Cake', 'Cake'), ('Bread', 'Bread'), ('Pastry', 'Pastry'), ('Other', 'Other')], max_length=6)),
                ('product_price', models.DecimalField(db_column='Product_price', decimal_places=2, max_digits=8)),
                ('product_shelf_life_seconds', models.PositiveSmallIntegerField(db_column='Product_shelf_life_seconds')),
                ('is_deleted', models.BooleanField(db_column='Is_deleted', default=False)),
            ],
            options={
                'db_table': 'Products',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SaleProducts',
            fields=[
                ('pk', models.CompositePrimaryKey('sale_id', 'product_id', blank=True, editable=False, primary_key=True, serialize=False)),
                ('product_quantity', models.PositiveSmallIntegerField(db_column='Product_quantity')),
                ('is_deleted', models.BooleanField(db_column='Is_deleted', default=False)),
            ],
            options={
                'db_table': 'Sale_products',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Sales',
            fields=[
                ('sale_id', models.AutoField(db_column='Sale_ID', primary_key=True, serialize=False)),
                ('sale_date_time', models.DateTimeField(db_column='Sale_date_time')),
                ('is_card_payment', models.BooleanField(db_column='Is_card_payment')),
                ('is_deleted', models.BooleanField(db_column='Is_deleted', default=False)),
            ],
            options={
                'db_table': 'Sales',
                'managed': False,
            },
        ),
    ]
