# Generated by Django 6.0.2 on 2026-03-11 12:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stock_management_ui', '0002_create_groups'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Deliveries',
        ),
        migrations.DeleteModel(
            name='DeliveryItems',
        ),
    ]
